### ISSUE TITLE
Cannot find module crypto

### ISSUE THREAD

**Issue by josiahking** [xama5/generate-password-browser#6]
Am getting error, could not find main module: Error: Cannot find module crypto at randombytes/index.js:1:80

**Comment by oliver-la** [comment]
Please provide more details and a reproducable example.

**Comment by josiahking** [comment]
Am working on a mobile app using tabrisjs, so i tried to generate password. After installing the npm package, i required it in my file, when i reload the developer app, i get that error in my console.

**Comment by oliver-la** [comment]
Looks like tabrisjs doesn't use browser.js from the crypto dependency. This is not a bug in my package, it's a bug from tabrisjs.

**Comment by josiahking** [comment]
Thanks for the clarification.
