### ISSUE TITLE
Causes Buffer to be included in Webpack build

### ISSUE THREAD

**Issue by Studio384** [xama5/generate-password-browser#7]
When building our package with Webpack, we've found that this package is resulting in Buffer being included into our build. Is there a way to omit it's inclusion?

**Comment by oliver-la** [comment]
Hi there

`generate-password-browser` itself does not include `Buffer`, but `randombytes` does: https://github.com/crypto-browserify/randombytes/blob/master/browser.js#L15

Is there a reason you want to omit its inclusion?

I wanted to keep the changes to `generate-password-browser` as minimal as possible, as to be able to easily merge any changes from upstream into this repo.
Of course I'm open to a PR to remove the randombytes dependency or use a different one, if the resulting bundle size is smaller or the compatibility with bundlers and browsers is improved. (Reduced randomness/security is however not acceptable.)

**Comment by oliver-la** [comment]
Closing due to no reply from issue author.

**Comment by Studio384** [comment]
My main issue is that with Webpack 5, these polyfils are no longer included by default.
