### ISSUE TITLE
Include lowercase config

### ISSUE THREAD

**Issue by jaffbeto** [xama5/generate-password-browser#8]
Argument of type '{ length: number; numbers: true; uppercase: true; lowercase: boolean; symbols: true; exclude: string; excludeSimilarCharacters: true; strict: true; }' is not assignable to parameter of type 'Options'.

 Object literal may only specify known properties, and 'lowercase' does not exist in type 'Options'.

![image](https://user-images.githubusercontent.com/17092218/101351577-104fa300-3891-11eb-930a-c5ab8a0a9ced.png)

Thank you!

**Comment by oliver-la** [comment]
Implemented in 6552491b4234ada625b298257c89b2f0cd2ab56a
