### ISSUE TITLE
JS file

### ISSUE THREAD

**Issue by Amplificator** [xama5/generate-password-browser#9]
Can I use this project in my own frontend? How would I produce a js file?

**Comment by oliver-la** [comment]
Of course you can. You're supposed to install it as a dependency to your project with npm/yarn. Using a bundler (gulp, parcel, laravel-mix, etc.) you can produce the js file for your project. 

Here's an example how to implement this library: https://github.com/oliver-la/generate-password-browser/blob/master/example.js

**Comment by Amplificator** [comment]
I have generated this file now: https://paste.mozilla.org/044YQcOF
But generate() doesn't work (not defined) - how do I generate a password?

**Comment by oliver-la** [comment]
How did you generate it? Describe your process.

**Comment by Amplificator** [comment]
I have created another js file now. I added generate-password-browser and browserify to my npm project and ran:

`mkdir -p ./dist/assets/js/ && browserify ./node_modules/generate-password-browser/main.js -o ./dist/assets/js/password.js`

That produces this js file: https://paste.mozilla.org/aURYynN9
..but I can't seem to run the generate() function?

**Comment by oliver-la** [comment]
Okay, now I'm seeing what you're trying to do. First, thank you for trying to find a solution by yourself!

I see you have installed generate-password-browser using npm. As a bundler you opted for browserify.

You never build dependencies directly, like you did above. They cannot run on their own, and so you can't run any functions either. Exception: Sometimes package maintainers include "dist" files in their repositories, which are designed to run on their own. My repository doesn't contain these however.

Let's try to implement my library:

1) Create a .js file in your project folder, this will be the file you're going to build with browserify.

````
var generator = require('generate-password-browser');

document.write(generator.generate());
````

2) Then build it with browserify:  browserify your-file.js -o ./dist/assets/js/app.js

Once you load that built js file in your browser, you should see a random password on your page. Of course you'll want to do something more meaningful than document.write(), simply add your stuff to the file and you're set.
Please note that with the above you will not be able to use the "generator" variable in your developer console. Files you build are always "isolated", unless they explicitly make the variables global.

To make the generator global (i.e. being able to use it in the developer console), simply do this in your .js file:

````
window.generator = generator;
````


---


I recommend to use something different than browserify. It gets the job done, but will produce huge .js files. Proper bundlers can minify the files and do optimizations. (and also watch your files for changes, so you don't have to build the js file manually yourself every time)

**Comment by Amplificator** [comment]
Thank you, those instructions produced a js file I could use in my regular html file :)
